name: Hexo CI/CD

on:
  push:
    branches: [ main, master ]
  schedule:
    # 每天 UTC 时间 0 点自动构建（可选）
    - cron: '0 0 * * *'

env:
  NODE_VERSION: '18'

jobs:
  pages:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive  # 检查子模块（主题）
        
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
        
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Build
      run: |
        npx hexo clean
        npx hexo generate
        
    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
        force_orphan: true  # 保持 gh-pages 分支清洁
        commit_message: "Deploy: ${{ github.event.head_commit.message }}"
        
    - name: Notify success
      if: success()
      run: |
        echo "✅ 网站部署成功！"
        
    - name: Notify failure
      if: failure()
      run: |
        echo "❌ 部署失败，请检查日志"